In [1]:
#Importing numpy
import numpy as np

### Make a 1D Array and check shape, size, dimension and length

In [6]:
#Creating a 1D array
arr = np.array([1, 2, 3, 4, 5])
shape = arr.shape

#Checking size
size = arr.size

#Checking dimensions
dimensions = arr.ndim

#Checking length
length = len(arr)

# Printing the results
print("Shape:", shape)
print("Size:", size)
print("Dimensions:", dimensions)
print("Length:", length)

Shape: (5,)
Size: 5
Dimensions: 1
Length: 5


### Make a 2D Array and check shape, size, dimension and length

In [7]:
#Creating a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

#Checking shape
shape = arr_2d.shape

#Checking size
size = arr_2d.size

#Checking dimensions
dimensions = arr_2d.ndim

#Checking length
length = len(arr_2d)

#Printing the results
print("Shape:", shape)
print("Size:", size)
print("Dimensions:", dimensions)
print("Length:", length)

Shape: (2, 3)
Size: 6
Dimensions: 2
Length: 2


### Make a 3D Array and check shape, size, dimension and length

In [8]:
#Creating a 3D array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

#Checking shape
shape = arr_3d.shape

#Checking size
size = arr_3d.size

#Checking dimensions
dimensions = arr_3d.ndim

#Checking length
length = len(arr_3d)

#Printing the results
print("Shape:", shape)
print("Size:", size)
print("Dimensions:", dimensions)
print("Length:", length)

Shape: (3, 2, 2)
Size: 12
Dimensions: 3
Length: 3


### Write an example for the function: random.randint

In [9]:
#Creating an array using arange
arr = np.arange(1, 10, 2)

#Displaying the array
print(arr)

[1 3 5 7 9]


### Write an example for the function: random.randint

In [10]:
#Generating 5 random integers between 1 and 100
random_integers = np.random.randint(1, 101, 5)

#Displaying the random integers
print(random_integers)

[71 26 32 34 16]


### Write an example for the function: random.rand

In [11]:
#Generating a 2x3 array of random numbers between 0 and 1
random_array = np.random.rand(2, 3)

#Displaying the random array
print(random_array)

[[0.21443574 0.4989025  0.86959166]
 [0.5852726  0.66385915 0.3518034 ]]


### Write an example for the function: linspace

In [12]:
#Generating 10 equally spaced points between 1 and 5
points = np.linspace(1, 5, 10)

#Displaying the generated points
print(points)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


### Write an example for the function: ones

In [13]:
#Creating a 2x3 array filled with ones
ones_array = np.ones((2, 3))

#Displaying the array filled with ones
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


### Write an example for the function: zeros

In [14]:
#Creating a 3x2 array filled with zeros
zeros_array = np.zeros((3, 2))

#Displaying the array filled with zeros
print(zeros_array)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


### Write an example for the function: diag

In [15]:
#Creating a diagonal array with specified diagonal elements
diagonal_array = np.diag([1, 2, 3])

#Displaying the diagonal array
print(diagonal_array)

#Extracting diagonal elements from a 2D array
arr_2d = np.array([[4, 5, 6], [7, 8, 9], [10, 11, 12]])
diagonal_elements = np.diag(arr_2d)

#Displaying the extracted diagonal elements
print(diagonal_elements)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[ 4  8 12]


### Write an example for the function: sum

In [16]:
#Creating an array
arr = np.array([[1, 2], [3, 4]])

#Calculating the sum of all elements in the array
total_sum = np.sum(arr)

#Calculating the sum along a specific axis (axis=0 for columns, axis=1 for rows)
column_sum = np.sum(arr, axis=0)
row_sum = np.sum(arr, axis=1)

#Displaying the results
print("Total Sum:", total_sum)
print("Column Sum:", column_sum)
print("Row Sum:", row_sum)

Total Sum: 10
Column Sum: [4 6]
Row Sum: [3 7]


### Write an example for the function: min

In [17]:
#Example of using the min function in numpy
array = np.array([5, 2, 8, 1, 9])
smallest_number = np.min(array)

print("The smallest number in the array is:", smallest_number)

The smallest number in the array is: 1


### Write an example for the function: max

In [ ]:
#Example of using the max function in numpy
array = np.array([5, 2, 8, 1, 9])
largest_number = np.max(array)

print("The largest number in the array is:", largest_number)

### Write an example for the function: mean

In [18]:
#Example of using the mean function in numpy
array = np.array([5, 2, 8, 1, 9])
mean_value = np.mean(array)

print("The mean of the array is:", mean_value)

The mean of the array is: 5.0


### Make an array of student marks of a course by generating marks using random between the values 0 to 100. Assume failing criteria is scoring less than 30 marks. Find the number of students who passed and filter the failed marks.

In [20]:
import random

#Random marks for 50 students
student_marks = [random.randint(0, 100) for i in range(50)]

#Find the number of students who passed (marks >= 30)
passed_students = sum(mark >= 30 for mark in student_marks)

#Filter out the failed marks into a separate list
failed_marks = [mark for mark in student_marks if mark <= 30]

print("Student Marks:", student_marks)
print("Number of Students Passed:", passed_students)
print("Failed Marks List:", failed_marks)

Student Marks: [11, 0, 56, 93, 9, 100, 45, 57, 36, 82, 68, 100, 33, 38, 2, 31, 41, 83, 81, 79, 81, 29, 20, 30, 96, 97, 84, 50, 37, 79, 77, 98, 73, 25, 97, 12, 43, 0, 18, 90, 15, 40, 58, 6, 83, 38, 7, 56, 79, 14]
Number of Students Passed: 36
Failed Marks List: [11, 0, 9, 2, 29, 20, 30, 25, 12, 0, 18, 15, 6, 7, 14]


### Make a 2D array with random numbers between 1 to 50.

In [21]:
#Dimensions of the 2D array
rows = 5
cols = 5

#2D array with random numbers between 1 to 50
random_2d_array = np.random.randint(1, 51, size=(rows, cols))

print("2D Array with Random Numbers between 1 to 50:")
print(random_2d_array)

2D Array with Random Numbers between 1 to 50:
[[ 3 31  8 24 43]
 [16 26 30 16 17]
 [32  2 28 32 31]
 [ 1  7 26 16 40]
 [48 44 40 35 33]]
